name: Deploy to AWS

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Build, tag, and push Docker image
        run: |
          docker build -t gallery-service .
          docker tag gallery-service:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Deploy to EC2
        run: |
          ssh -o "StrictHostKeyChecking=no" ec2-user@<EC2_INSTANCE_IP> \
          "docker pull ${{ secrets.ECR_REPOSITORY_URI }}:latest && \
           docker stop gallery-service || true && \
           docker rm gallery-service || true && \
           docker run -d -p 80:3000 gallery-service:latest"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
