import { Profile } from "../libs/models/profile/models/profile.model";

export const profiles: any | Omit<Profile, '_id'>[] = [
  {
    name: 'John Doe',
    email: 'john.doe@me.com',
    location: {
      distance: 25,
      title: 'Regensburg, Germany',
      lat: 48.137,
      long: 12.101,
      coordinates: [12.101, 48.137],
    },
    website: 'https://github.com/zimoykin',
    url: 'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/24/24feebb92301fb4efeb3d0956024e33293b78c57_full.jpg',
    privateAccess: true,
    userId: '1',
  },
  {
    name: 'Alessandra Bohne',
    email: 'jane.bohne@me.com',
    location: {
      distance: 25,
      title: 'Nuremberg, Germany',
      lat: 49.454,
      long: 11.076,
      coordinates:  [11.076, 49.454],
    },
    website: 'https://github.com/zimoykin',
    url: 'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/1f/1f8ced3635f9a2a7d71bcb4a41fe006b9d9dc996_full.jpg',
    privateAccess: true,
    userId: '2',
  },
  {
    name: 'Freddy Kowalski',
    email: 'fred.kowalski@me.com',
    location: {
      distance: 50,
      title: 'Munich, Germany',
      lat: 48.137,
      long: 11.581,
      coordinates:[11.581, 48.137],
    },
    website: 'https://github.com/zimoykin',
    url: 'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShaggyMullet&accessoriesType=Wayfarers&hairColor=Black&facialHairType=MoustacheFancy&facialHairColor=Red&clotheType=CollarSweater&clotheColor=PastelYellow&eyeType=Cry&eyebrowType=Angry&mouthType=Serious&skinColor=Tanned',
    privateAccess: true,
    userId: '4',
  },
  {
    name: 'Mary Smith',
    email: 'mary.smith@me.com',
    location: {
      distance: 50,
      title: 'Augsburg, Germany',
      lat: 48.366512,
      long: 10.894446,
      coordinates: [10.894446, 48.366512],

    },
    website: 'https://avatar.iran.liara.run/public/24',
    url: 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairStraight&accessoriesType=Blank&hairColor=BrownDark&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light',
    privateAccess: true,
    userId: '5',
  },
  {
    name: 'Dr. Dan Brown',
    email: 'dr.dan.brown@me.com',
    location: {
      distance: 50,
      title: 'Freising, Germany',
      lat: 48.37,
      long: 11.81,
      coordinates:  [11.81, 48.37],
    },
    website: 'https://avatar.iran.liara.run/public/24',
    url: 'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/33/33ed774eb2384310de7dc2503b866b10aa86899f.jpg',
    privateAccess: false,
    userId: '6',
  },
  {
    url: 'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/10/10067c33a4fe0f459f9491eb3010f1fe12876333.jpg',
    name: 'Renee Miller',
    email: 'renee.miller@me.com',
    location: {
      distance: 50,
      title: 'Ingolstadt, Germany',
      lat: 48.765,
      long: 11.371,
      coordinates: [11.371, 48.765],
    },
    website: 'https://github.com/zimoykin',
    privateAccess: false,
    userId: '7',
  }
];
